### ISSUE TITLE
Some questions, couldn't find any other way to contact you

### ISSUE THREAD

**Issue by AAGaming00** [kum4423/local_manifest#1]
heyo! i've been working on properly porting this rom to the US starqlte/star2qlte/crownqlte. i have it booting fine right now (both your build + custom kernel and my build with the correct kernel) but am hitting some vendor service weirdness (will detail more on this when i have a chance). also looked around and saw that you mentioned a telegram group somewhere on an old XDA post, but i can't find the group itself. 

any pointers?
(for private replies, aagaming@riseup.net. PGP is fine if preferred, same key as this github account)

**Comment by kum4423** [comment]
TG: kum4423
